///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String assetsGithubMark = 'assets/github-mark.png';
  static const String assetsGoogleLogo = 'assets/google_logo.png';
}
